FROM node:18-slim

EXPOSE 8080

WORKDIR /app
COPY ./ecosystem.config.js ./

WORKDIR /app/feed-crawler
COPY ./feed-crawler/package*.json ./
RUN npm ci && npm cache clean --force && npm install -g pm2 typescript

WORKDIR /app/server
COPY ./server/package*.json ./
RUN npm ci && npm cache clean --force

WORKDIR /app/feed-crawler
COPY ./feed-crawler ./
RUN tsc

WORKDIR /app/server
COPY ./server ./
RUN npm run build

WORKDIR /app

CMD ["pm2-runtime", "start", "ecosystem.config.js"]