FROM keymetrics/pm2

WORKDIR /app

COPY ./server/package*.json ./server
WORKDIR /app/server
RUN npm ci

WORKDIR /app
COPY ./feed-crawler/package*.json ./feed-crawler
WORKDIR /app/feed-crawler
RUN npm ci

WORKDIR /app
COPY ./server ./server
COPY ./feed-crawler ./feed-crawler

WORKDIR /app/server
RUN npm run build

WORKDIR /app/feed-crawler
RUN tsc

EXPOSE 8080

WORKDIR /app

CMD ["pm2-runtime", "start", "ecosystem.config.js"]