name: Server Deployment

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  workflow_dispatch: # 수동 실행을 허용하는 이벤트

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # public 서버로 ssh 접속
      - name: ssh connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            cd refactor-web41-Denannu
            git pull origin main

            cd server

            echo "${{ secrets.ENV_BE_DB}}" > configs/.env.db.production

            cd ..
            cd feed-crawler/
            echo "${{ secrets.ENV_BE_RSS }}" > .env
            cd ..

            docker compose up -d --build server
